name: Run SQL Queries in Snowflake from a File

on:
  push:
    branches:
      - main
    paths:
      - 'sql/**'

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Execute SQL Queries from File
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          python - <<EOF
          import os
          import snowflake.connector

          # Get the SQL file path from the workflow input
          sql_file_path = "${{ github.workspace }}/" + os.getenv("INPUT_SQL_FILE_PATH")

          if not os.path.exists(sql_file_path):
              raise FileNotFoundError(f"SQL file not found: {sql_file_path}")

          # Read SQL queries from the file
          with open(sql_file_path, 'r') as file:
              sql_queries = file.read()

          # Connect to Snowflake
          conn = snowflake.connector.connect(
              account=os.getenv("SNOWFLAKE_ACCOUNT"),
              user=os.getenv("SNOWFLAKE_USER"),
              password=os.getenv("SNOWFLAKE_PASSWORD"),
              role=os.getenv("SNOWFLAKE_ROLE"),
              database=os.getenv("SNOWFLAKE_DATABASE"),
              warehouse=os.getenv("SNOWFLAKE_WAREHOUSE")
          )

          # Execute the queries
          try:
              with conn.cursor() as cursor:
                  for query in sql_queries.split(';'):
                      query = query.strip()
                      if query:
                          print(f"Executing query: {query}")
                          cursor.execute(query)
                          for row in cursor:
                              print(row)
              print("All queries executed successfully.")
          finally:
              conn.close()
          EOF
